const ASESORES = [
  {
    id: "85",
    dsnombre: "Daniela",
    dsnombre2: "",
    dsapellido1: "Gomez",
    dsapellido2: "Isaza",
    dscorreo: "daniela.gomez@aveonline.co",
    dstel: "3054202125",
    hubspot: "70597443",
  },
  {
    id: "113",
    dsnombre: "Jhoana",
    dsnombre2: "Andrea",
    dsapellido1: "Pineda",
    dsapellido2: "Munoz",
    dscorreo: " sc1@aveonline.co",
    dstel: "4488799",
    hubspot: "77178430",
  },
  {
    id: "239",
    dsnombre: "Leidy",
    dsnombre2: "Katherine",
    dsapellido1: "Molina",
    dsapellido2: "Calle",
    dscorreo: "coordinadorsc@aveonline.co",
    dstel: "3023640277",
    hubspot: "75346701",
  },
  {
    id: "262",
    dsnombre: "Carolina",
    dsnombre2: "",
    dsapellido1: "Cordoba",
    dsapellido2: "Callejas",
    dscorreo: "comercial1@aveonline.co",
    dstel: "3054202125",
    hubspot: "72348318",
  },
  {
    id: "280",
    dsnombre: "Maria ",
    dsnombre2: "Alejandra",
    dsapellido1: "Muriel ",
    dsapellido2: "Molina",
    dscorreo: "sc3@aveonline.co",
    dstel: "4488799",
    hubspot: "77171403",
  },
  {
    id: "295",
    dsnombre: "Santiago",
    dsnombre2: "",
    dsapellido1: "Castano",
    dsapellido2: "Arboleda",
    dscorreo: "sc12@aveonline.co",
    dstel: "4488799",
    hubspot: "77171218",
  },
  {
    id: "301",
    dsnombre: "Laura",
    dsnombre2: "",
    dsapellido1: "Galeano",
    dsapellido2: "Betancur",
    dscorreo: "sc11@aveonline.co",
    dstel: "4488799",
    hubspot: "77171185",
  },
  {
    id: "302",
    dsnombre: "Andres",
    dsnombre2: "Felipe",
    dsapellido1: "Molina",
    dsapellido2: "Arroyave",
    dscorreo: "sc13@aveonline.co",
    dstel: "4488799",
    hubspot: "77171468",
  },
  {
    id: "304",
    dsnombre: "YASMIN",
    dsnombre2: "ALEXANDRA",
    dsapellido1: "CORTES",
    dsapellido2: "RESTREPO",
    dscorreo: "comercial2@aveonline.co",
    dstel: "3122927766",
    hubspot: "72558355",
  },
  {
    id: "308",
    dsnombre: "Amalia",
    dsnombre2: "",
    dsapellido1: "Garcia",
    dsapellido2: "",
    dscorreo: "sc2@aveonline.co",
    dstel: "4488799",
    hubspot: "77171246",
  },
  {
    id: "1009",
    dsnombre: "Juan",
    dsnombre2: "Manuel",
    dsapellido1: "Yepes",
    dsapellido2: "Rodriguez",
    dscorreo: "comercial3@aveonline.co",
    dstel: "3043293149",
    hubspot: "73166873",
  },
];
// .map(e=>({"id": e.id,
//     "dsnombre": e.dsnombre,
//     "dsnombre2": e.dsnombre2,
//     "dsapellido1":e.dsapellido1,
//     "dsapellido2": e.dsapellido2,
//     "dscorreo": e.dscorreo,
//     "dstel": e.dstel,
//     "hubspot": e.hubspot})).filter(e=>e.hubspot)
module.exports = {
  ASESORES,
};
